import QtQuick
import Licasa 1.0

// Lazily loaded bridge for the native Motion Photo presentation item.
// Importing Licasa activates the C++ type registrar generated by
// qt_add_qml_module; ImageViewport itself remains usable as a plain local QML
// component in QuickTest and on ordinary still-image startup.
MotionPhotoFrameSurface {
    objectName: "motionPhotoFrameSurface"
}
